name = "WAVIPlotting"
uuid = "1f02478e-a41e-41fb-826c-1dc83af65e00"
version = "0.0.1"
authors = ["Bryn Noel Ubald <55503826+bnubald@users.noreply.github.com>"]

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
ArgParse = "1.2.0"
GLMakie = "0.13.7"
NCDatasets = "0.14.10"
Plots = "1.41.2"

[comonicon]
bin_dir = "bin"
modules = ["WAVIPlotting.CLI"]
